@url = https://friendly-disco-97jp9gjgxj792xjxj-3000.app.github.dev/

GET {{url}}/api/v1/generos

###

POST {{url}}/api/v1/generos
Content-Typoe: application/json

{
    "id": 10,
    "nome" : "Biografia"
}